http:
  middlewares:
    basic-auth:
      basicAuth:
        users:
          - "admin:$apr1$AH.V2qSj$nfPYFpud51GKch695h/.41"
        realm: "Security ERP"

    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        frameDeny: true
