http:
  middlewares:
    basic-auth:
      basicAuth:
        users:
          - "joker:$apr1$UChSy978$lQQ9arJlqEgB4HE2YXjNJ."
        realm: "Security ERP"

    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        frameDeny: true
