http:
  routers:
    erpnext:
      rule: "Host(`erp.localhost`) || Host(`erp.riad.fun`)"
      entrypoints:
        - web
      service: erpnext

  services:
    erpnext:
      loadBalancer:
        servers:
          - url: "http://erpnext-frontend:8080"

  middlewares:
    basic-auth:
      basicAuth:
        users:
          - "joker:$apr1$UChSy978$lQQ9arJlqEgB4HE2YXjNJ."
        realm: "Security ERP"

    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        frameDeny: true
