tunnel: fe711e37-f560-45d6-aaf1-db7a208280de
credentials-file: /etc/cloudflared/creds.json

ingress:
  - hostname: mimo.riad.fun
    service: http://host.docker.internal:8931
    originRequest:
      noTLSVerify: true
  - hostname: erp.riad.fun
    service: http://erpnext-frontend:8080
  - hostname: api.riad.fun
    service: http://security-api:8000
  - hostname: n8n.riad.fun
    service: http://n8n:5678
  - hostname: grafana.riad.fun
    service: http://grafana:3000
  - service: http_status:404
